# Generated by Django 4.2.13 on 2024-05-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Roomie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomie_id", models.IntegerField(default=0, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("number_of_roommates", models.IntegerField(default=0)),
                ("roommate_ids", models.JSONField()),
            ],
        ),
    ]
