# Generated by Django 4.2.13 on 2024-05-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.IntegerField(
                choices=[(0, "Chore"), (1, "Visitor"), (2, "Reservation")], default=0
            ),
        ),
    ]
