# Generated by Django 4.2.13 on 2024-05-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_task_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="allergy",
            field=models.BooleanField(default=False),
        ),
    ]
