# Generated by Django 4.2.13 on 2024-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_allergy_remove_rule_allergy_roomie_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomie",
            name="roommate_ids",
            field=models.JSONField(default=list),
        ),
    ]
