# Generated by Django 4.2.13 on 2024-05-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_roomie_roommate_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allergy",
            name="roomie_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="rule",
            name="agreement_roomie_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="rule",
            name="disagreement_roomie_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="task",
            name="tasks",
            field=models.TextField(),
        ),
    ]
