# Generated by Django 4.2.13 on 2024-05-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_allergy_roomie_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="roommate_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="roommate_ids",
            field=models.JSONField(default=list),
        ),
    ]
